name: Prebuild Binaries

on:
  pull_request:

jobs:
  prebuild-linux:
    name: Prebuild Binaries for Linux
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Setup Dependencies
        run: |
          sudo apt-get update -y -qq
          sudo apt-get install -y g++-multilib gcc-multilib libcups2-dev linux-libc-dev
      - uses: actions/setup-node@v1
        with:
          node-version: 22.x
      - uses: actions/checkout@v1
      - run: npm i
      - name: Prebuild
        run: |
          npm run prebuild -- -r node -t 22.0.0 --strip --arch x64
          npm run prebuild -- -r electron -t 38.0.0 --strip --arch x64
  prebuild-macos:
    name: Prebuild Binaries for macOS
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 22.x
      - uses: actions/checkout@v1
      - run: npm i
      - name: Prebuild
        run: |
          npm run prebuild -- -r node -t 22.0.0 --strip --arch x64
          npm run prebuild -- -r electron -t 38.0.0 --strip --arch x64
  prebuild-windows:
    name: Prebuild Binaries for Windows
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 22.x
      - uses: actions/checkout@v1
      - run: npm i
      - name: Prebuild
        run: |
          npm run prebuild -- -r node -t 22.0.0 --strip --arch x64
          npm run prebuild -- -r electron -t 38.0.0 --strip --arch x64
